### PR TITLE
make facts.sh sh compatible

### PR DESCRIPTION
**Pull request by mookie-**
[[ are bash builtin and not supported by sh

### CODE REVIEW

**Comment by mookie-** [comment]
#82

**Comment by alexjfisher** [comment]
@mookie- Thanks.  Very small nitpick. - spelling of 'compatible' in commit message.

Other than that, the change looks correct (eg $VERSION is correctly quoted, `-z` is available in posix shells etc)
http://mywiki.wooledge.org/BashFAQ/031

**Comment by mookie-** [comment]
Thanks @alexjfisher 
I'm sorry. I should have been more careful.

**Comment by alexjfisher** [comment]
@mookie- No worries.  Thanks for your PR and thanks for updating the commit.  Merged.

**Pull request merged**
