### PR TITLE
feat: stdlib9 and puppet8 compatibility

### PR DESCRIPTION
**Pull request by dploeger**
#### Pull Request (PR) description
This adds stdlib 9 and Puppet 8 compatibility. Didn't break on our side.

#### This Pull Request (PR) fixes the following issues
n/a

### CODE REVIEW

**Comment by dploeger** [comment]
Hm. Did I miss to change something for the tests? It complains about that the stdlib 8 is already installed...

**Comment by kenyon** [comment]
Probably need #232 first.

**Comment by h-haaks** [comment]
I think you'll have to allow puppet/archive 7.x and puppet/mysql_java_connector 6.x as well.

**Comment by h-haaks** [comment]
Fixes #204

**Comment by h-haaks** [comment]
@dploeger could you please rebase your branch and then allow puppet/archive 7.x and puppet/mysql_java_connector 6.x ?

**Comment by dploeger** [comment]
@h-haaks Done

**Comment by dploeger** [comment]
Great! Thanks. Could you kindly add an info to this PR when you've released a new version with this?

**Comment by kenyon** [comment]
@dploeger check out https://newreleases.io/ for release notifications, it works quite well.

**Comment by dploeger** [comment]
We're already using the RSS feeds on the forge. Still, a comment on a PR reaches me faster. 😊

**Comment by h-haaks** [comment]
@dploeger version 6.0.0 has now been release to forge.

**Pull request merged**
