### PR TITLE
Fix lint warning

### PR DESCRIPTION
**Pull request by h-haaks**
#### Pull Request (PR) description
Trying to cleanup failing tests

### CODE REVIEW

**Comment by bastelfreak** [comment]
this branch seems to be out of date. can you please rebase against our latest master branch? (this should remove the Puppet 5 CI job).

**Comment by h-haaks** [comment]
@bastelfreak do you know how I could run the acceptance test locally? There is no litmus rake tasks available and no beaker node definitions ...

**Comment by bastelfreak** [comment]
it doesn't look like your branch is based on the modulesync, because the modulesync changes aren't included here. To run the beaker jobs locally, you can do:
```
BEAKER_destroy=no BEAKER_PUPPET_COLLECTION=puppet7 BEAKER_setfile=centos8-64 BEAKER_HYPERVISOR=vagrant_libvirt bundle exec rake beaker
```

Instead of `vagrant_libvirt`, you can also specify `beaker`. The nodeset will be generated on the fly.

**Comment by h-haaks** [comment]
The pull request is for voxpupuli:modulesync. That's why there is mo modulesync changes :)

**Comment by h-haaks** [comment]
I guess I could rebase my branch against master and keep all the changes from the modulesync branch.

**Pull request closed without merging**
