### PR TITLE
Make confluence_version a First Class Fact

### PR DESCRIPTION
**Pull request by spjmurray**
This stems from the fact that the confluence module unconditionally manages the
directory /etc/puppetlabs/facter/facts.d directory in the sense that if the code
gets evaluated first you run into the age old race condition of clashing with other
classes who wish to manage it.  This removes said management, moves the fact
to a ruby/puppet native which yields slightly prettier and less code.  Transitional
code has been put in place to remove the old fact.

The `confluence::service` class is dependant on the old inherits which used to live
in `confluence::facts` to get access to `confluence::params`.  I've moved this to
the more socially acceptable top level class.

### CODE REVIEW

**Comment by spjmurray** [comment]
Hanging my head in shame @dhoppe - `ps` call is fixed to what it should have been, and the old fact is being purged now

**Comment by dhoppe** [comment]
@bastelfreak You do not use our module? Shame on you. 

I think the version is detected via the variable `webappdir` which you do not use. 
https://github.com/voxpupuli/puppet-confluence/blob/master/templates/confluence.initscript.erb#L27.

**Comment by dhoppe** [comment]
@voxpupuli/collaborators I am OK with this PR. Can somebody please verify that this works for RedHat 7? Because it uses a different template to start/stop the service.

**Comment by dhoppe** [comment]
@spjmurray Thx for your contribution.

**Pull request merged**
