### PR TITLE
Add support for configuring an AJP connector

### PR DESCRIPTION
**Pull request by JCotton1123**
Partially addresses https://github.com/voxpupuli/puppet-confluence/issues/54

### CODE REVIEW

**Comment by juniorsysadmin** [comment]
@JCotton1123 Merge conflicts

**Comment by JCotton1123** [comment]
@juniorsysadmin rebased

**Comment by juniorsysadmin** [comment]
@JCotton1123 Would be great if there were some additional tests for this

**Comment by sacres** [comment]
The puppet-jira module has tests for ajp, should be re-usable here I'd
think.

**Comment by JCotton1123** [comment]
Tests implemented

**Pull request merged**
