### PR TITLE
drop EOL Ubuntu 14.04

### PR DESCRIPTION
**Pull request by bastelfreak**

### CODE REVIEW

**Comment by dhoppe** [comment]
You also might want to add support for Debian 10 and enable the acceptance tests. Or should we do this in a separate pull request?

**Comment by bastelfreak** [comment]
@ekohl updated README.md. @dhoppe IMO debian 10 should be handled in another PR, because that would be a new feature.

**Comment by dhoppe** [comment]
Ok, but the README.md still contains CentOS 5.

**Comment by bastelfreak** [comment]
@dhoppe fixed it

**Pull request merged**
