### PR TITLE
Update based on voxpupuli/modulesync_config

### PR DESCRIPTION
**Pull request by dhoppe**
Please merge. I disabled the check ```variable_contains_upcase``` until we fixed this and have a better code coverage.

### CODE REVIEW

**Comment by jyaworski** [comment]
Invalid resource types?

**Comment by dhoppe** [comment]
I do not know, but I will fix this during the weekend. I am pretty sure that ```puppet-jira``` will also fail.

**Comment by dhoppe** [comment]
@jyaworski I think we should remove the tests for [deploy](https://github.com/voxpupuli/puppet-confluence/blob/master/spec/classes/confluence_install_deploy_spec.rb) and migrate to ```voxpupuli/archive``` as @mkrakowitzer did for ```voxpupuli/stash```.

There is a lot to do like implementing class parameters, renaming the parameters (variable_contains_upcase) and implementing more RSpec and Beaker tests.

**Comment by dhoppe** [comment]
This is failing because the error message does not fit at Puppet 4 and I do not know, why #43 was closed. To me it makes sense to set javahome to undef and throw an error message via fail. This is exactly what we should do for the jira and stash modules, too.

**Pull request merged**
